### ISSUE TITLE
Incorrect Requirements mentioned

### ISSUE THREAD

**Issue by shivergard** [gagliardetto/solana-go#250]
Building example gave me error:

# github.com/gagliardetto/solana-go/rpc/jsonrpc
../../../../../go/pkg/mod/github.com/gagliardetto/solana-go@v1.11.0/rpc/jsonrpc/jsonrpc.go:535:28: undefined: atomic.Uint64
note: module requires Go 1.19

As said - it looks like minimal version of Golang is not 1.18 , but 1.19++

**Comment by shivergard** [comment]
The problem is :
`var integerID = new(atomic.Uint64)`
it is not supported in 1.18. It can be updated for 
`var integerID = new(uint64)`
and in function newID   I've changed it to:

`func newID() any {
	if useFixedID {
		return defaultFixedID
	}
	if UseIntegerID {
        atomic.AddUint64(integerID,1)
		return integerID
	}
	return uuid.New().String()
}`

code does build on 1.18 , but not sure what it changes - so most probably you should update min Requirements in readme

**Comment by gagliardetto** [comment]
Updated, thanks!
